### ISSUE TITLE
link to fine-tuned model does not work

### ISSUE THREAD

**Issue by jmorgan-wellovate** [liuff19/Sherpa3D#3]
link to fine-tuned model is a dead link

**Comment by wdkkkk** [comment]
Thanks. Cap3D has changed their project structure, which made the original path to the pre-trained model invalid. You can try the following two links: https://huggingface.co/datasets/tiange/Cap3D/blob/main/misc/our_finetuned_models/shapE_finetuned_with_330kdata.pth 
https://huggingface.co/datasets/tiange/Cap3D/blob/main/misc/our_finetuned_models/shapE_finetuned_with_825kdata.pth
