### ISSUE TITLE
Cannot perform on one single RTX3090

### ISSUE THREAD

**Issue by Colezwhy** [liuff19/Sherpa3D#4]
Thank you for your great work!
But in the paper, it says the whole pipeline can be performed with one RTX3090.
In my trial, one single RTX3090 might trigger CUDA out of memory.
Would you please provide some solutions?

**Comment by LinqingZhong** [comment]
@Colezwhy Hello, I met the same problem. May I ask how do you solve this problem?

**Comment by Colezwhy** [comment]
> @Colezwhy Hello, I met the same problem. May I ask how do you solve this problem?

Sorry, but I gave this up.

**Comment by lakpa-tamang9** [comment]
There might be other processes that is using your GPU. You can kill all background processes and clean run the code with bash. 

`nvidia-smi` gives your process and their IDs called PID.
`sudo kill -p PID` kills your process.

I also encountered CUDA OOM error, but after clearing the background processes i could run it successfully.
_PS: I also used RTX 3090 Ti_
